pipeline:
  build:
    image: python:2.7-alpine
    commands:
      - apk update && apk add zip
      - pip install -r requirements.txt -t .
      - zip -r -9 lambda-project-${DRONE_BUILD_NUMBER}.zip *

  s3-publish:
    image: plugins/s3
    #acl: private
    region: us-east-1
    bucket: surakshadrone
    target: drone
    source: lambda-project-${DRONE_BUILD_NUMBER}.zip

  deploy-lambda:
    image: omerxx/drone-lambda-plugin
    #region: us-west-2
    #pull: true
    function_name: suraksha
    s3_bucket: surakshadrone
    file_name: drone/revenue-report-${DRONE_BUILD_NUMBER}.zip
