kind: pipeline
name: default
workspace:
  base: /tmp
  path: "."
steps:
- name: build
  image: python:2.7-alpine
  commands:
    - apk update && apk add zip
    - pip install -r requirements.txt -t .
    - zip -r -9 lambda-project-${DRONE_BUILD_NUMBER}.zip *
- name: s3-publish
  image: plugins/s3
  acl: private
  region: us-west-2
  bucket: code-deploy12345
  target: lambda-dir
  source: lambda-project-${DRONE_BUILD_NUMBER}.zip 

